"use client";

import Link from "next/link";
import { useAppSettings } from "@/lib/appSettings";
import { resolveLocale } from "@/lib/i18n";

const CONTENT = {
  en: {
    title: "Terms of Service",
    updated: "Effective Date: January 17, 2026",
    intro:
      "These Terms of Service (\"Terms\") govern your access to and use of the Neuro Trader Journal website, applications, and related services (collectively, the \"Service\") provided by SG PAX CORP. (\"Neuro Trader Journal\", \"NTJ\", \"we\", \"us\", or \"our\").",
    important:
      "IMPORTANT: NTJ is a journaling, analytics, and educational/coaching platform. NTJ is not a broker-dealer, investment adviser, commodity trading advisor, or financial planner. Nothing in the Service is intended to be (or should be construed as) investment, trading, legal, tax, or accounting advice.",
    sections: [
      {
        title: "1. Acceptance of Terms",
        body:
          "BY ACCESSING OR USING THE SERVICE, YOU AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE, DO NOT ACCESS OR USE THE SERVICE. We may update these Terms from time to time. The updated Terms will be effective when posted or when otherwise made available to you. Your continued use of the Service after an update constitutes acceptance of the updated Terms.",
      },
      {
        title: "2. Description of the Service",
        body:
          "The Service may include features such as trade journaling, trade analytics, performance metrics, tagging and notes, screenshots and attachments, dashboards, integrations with third-party platforms, community or sharing features (if enabled), and AI-assisted coaching and insights. We may add, remove, or modify features at any time. You are responsible for obtaining and maintaining all devices, software, and internet access necessary to use the Service.",
      },
      {
        title: "3. Eligibility and Account Registration",
        body:
          "You must be legally able to enter into a binding contract in your jurisdiction to use the Service. You agree to provide accurate, current, and complete information when creating an account and to keep that information updated. You are responsible for maintaining the confidentiality of your login credentials and for all activities that occur under your account. Notify us immediately at support@neurotrader-journal.com if you suspect unauthorized access or use.",
      },
      {
        title: "4. Data Inputs, Integrations, and User Responsibility",
        body:
          "The accuracy and usefulness of journaling, analytics, metrics, and AI Coaching outputs depend on the quality and completeness of the data you provide and/or authorize NTJ to import through integrations. You are solely responsible for: (1) entering, uploading, or importing your trading data correctly and completely; (2) reviewing imported data for accuracy (including fills, commissions, fees, timestamps, and instrument details); (3) confirming that your broker, prop firm, or third-party platform data is accurate and reflects your official records; and (4) understanding how your broker/platform calculates metrics (e.g., realized vs. unrealized PnL, net vs. gross PnL). You acknowledge that third-party integrations may be unavailable, delayed, incomplete, or inaccurate due to third-party systems, permissions, API changes, outages, or other causes outside our control.",
      },
      {
        title: "5. AI Coaching and AI-Assisted Insights",
        body:
          "The Service may provide AI-assisted coaching, pattern detection, summaries, recommendations, trade reviews, risk/mindset prompts, and other automated insights (\"AI Coaching\"). AI Coaching is provided for informational and educational purposes only.",
      },
      {
        title: "5.1 AI May Be Inaccurate or Incomplete",
        body:
          "AI Coaching outputs are generated by automated systems and may contain errors, omissions, hallucinations, incorrect assumptions, or outdated information. We do not guarantee the accuracy, completeness, reliability, or usefulness of any AI Coaching output.",
      },
      {
        title: "5.2 AI Relies on Your Data and Context",
        body:
          "AI Coaching analyzes information based on the data you enter, upload, import, or otherwise provide (including trade data, notes, tags, and preferences). Because AI Coaching depends on your inputs, you are responsible for ensuring that your data is accurate and complete. Incorrect or incomplete inputs may produce misleading outputs.",
      },
      {
        title: "5.3 No Financial Advice; You Must Independently Evaluate",
        body:
          "AI Coaching is not investment advice, trading advice, or a recommendation to buy or sell any security, derivative, futures contract, forex pair, cryptocurrency, or any other instrument. Any actions you take based on AI Coaching are taken at your sole discretion and risk. You must independently evaluate any suggestion, recommendation, or analysis and decide whether to act.",
      },
      {
        title: "5.4 Assumption of Risk",
        body:
          "You assume all risks associated with relying on or using AI Coaching, including the risk of trading losses, missed opportunities, or adverse outcomes. NTJ disclaims all liability for decisions made based on AI Coaching.",
      },
      {
        title: "6. Trading Risk Disclosure",
        body:
          "Trading and investing involve substantial risk and are not suitable for all individuals. Past performance is not indicative of future results. You are solely responsible for determining whether any trading strategy, instrument, or approach is appropriate for you.",
      },
      {
        title: "7. User Conduct",
        body:
          "You agree not to use the Service to violate any applicable law or regulation; infringe intellectual property, privacy, publicity, or other rights; upload malware or attempt to disrupt, damage, or gain unauthorized access; harass, abuse, defame, or discriminate; misrepresent your identity or affiliation; or use the Service for unauthorized commercial solicitation or spam. We may investigate and take any action we deem appropriate, including removing content, suspending accounts, or terminating access, to enforce these Terms.",
      },
      {
        title: "8. User Content and Permissions",
        body:
          "You retain ownership of the content you submit to the Service (including trade data, notes, images, attachments, and other materials) (\"User Content\"). You grant NTJ a non-exclusive, worldwide, royalty-free license to host, store, process, reproduce, and display User Content as necessary to operate, improve, and provide the Service. If the Service offers sharing/public features and you choose to share User Content publicly, you understand that other users may view or access that content. You are responsible for ensuring that your User Content does not contain confidential information you are not authorized to share.",
      },
      {
        title: "9. Subscriptions, Billing, and Cancellations",
        body:
          "Certain features may require a paid subscription. Subscription fees are billed in advance on a recurring basis (e.g., monthly or annually) unless otherwise stated at checkout. You authorize us (and our payment processor) to charge your selected payment method. You may cancel your subscription at any time. Cancellation stops future renewals; you will retain access through the end of the current billing period unless otherwise required by law or stated in your plan details. Refunds: Except where required by law or explicitly stated in writing by NTJ, subscription fees are non-refundable. You are responsible for canceling your subscription before renewal to avoid additional charges.",
      },
      {
        title: "10. Third-Party Services and Links",
        body:
          "The Service may integrate with or link to third-party services (such as brokers, platforms, charting tools, analytics, or storage providers). Third-party services are not under our control. We do not endorse and are not responsible for third-party services, including their availability, accuracy, security, terms, or privacy practices.",
      },
      {
        title: "11. Intellectual Property",
        body:
          "The Service, including its software, design, logos, trademarks, and content provided by NTJ (excluding User Content), is owned by NTJ and/or its licensors and is protected by applicable intellectual property laws. Subject to your compliance with these Terms, NTJ grants you a limited, non-exclusive, non-transferable, revocable license to access and use the Service for your personal or internal business use.",
      },
      {
        title: "12. Disclaimers",
        body:
          "THE SERVICE (INCLUDING AI COACHING) IS PROVIDED ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS. TO THE MAXIMUM EXTENT PERMITTED BY LAW, NTJ DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR THAT ANY DATA OR RESULTS (INCLUDING METRICS, PNL, OR AI COACHING OUTPUTS) WILL BE ACCURATE OR RELIABLE.",
      },
      {
        title: "13. Limitation of Liability",
        body:
          "TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL NTJ OR ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, SUPPLIERS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, DATA, GOODWILL, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OF (OR INABILITY TO USE) THE SERVICE, INCLUDING ANY RELIANCE ON AI COACHING. TO THE MAXIMUM EXTENT PERMITTED BY LAW, NTJ'S TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF OR RELATING TO THE SERVICE WILL NOT EXCEED THE AMOUNT YOU PAID TO NTJ FOR THE SERVICE IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM. SOME JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS OF LIABILITY, SO SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.",
      },
      {
        title: "14. Indemnification",
        body:
          "You agree to defend, indemnify, and hold harmless NTJ and its Affiliates from and against any claims, damages, liabilities, losses, and expenses (including reasonable attorneys' fees) arising out of or related to your use of the Service, your User Content, your violation of these Terms, or your violation of any rights of another.",
      },
      {
        title: "15. Termination",
        body:
          "We may suspend or terminate your access to the Service at any time, with or without notice, if we reasonably believe you have violated these Terms or if we must do so to comply with law, protect the Service, or prevent harm. You may stop using the Service at any time. Upon termination, your right to use the Service will cease. Certain provisions of these Terms by their nature should survive termination, including intellectual property, disclaimers, limitation of liability, indemnification, and governing law.",
      },
      {
        title: "16. Governing Law and Dispute Resolution",
        body:
          "These Terms are governed by the laws of the jurisdiction in which NTJ is established, without regard to conflict-of-law principles. You agree that any dispute arising out of or relating to these Terms or the Service will be brought in the courts of competent jurisdiction in that location, unless applicable law provides otherwise.",
      },
      {
        title: "17. Notices",
        body:
          "We may provide notices to you via the Service, email, or other reasonable means. Notices to NTJ must be sent by email to support@neurotrader-journal.com.",
      },
      {
        title: "18. Miscellaneous",
        body:
          "Entire Agreement: These Terms constitute the entire agreement between you and NTJ regarding the Service. Severability: If any provision is held unenforceable, the remaining provisions will remain in effect. No Waiver: Failure to enforce any right or provision is not a waiver of such right or provision. Assignment: You may not assign your rights or obligations under these Terms without our consent; we may assign our rights and obligations. Force Majeure: We are not liable for delays or failures due to events beyond our reasonable control.",
      },
      {
        title: "19. Contact",
        body:
          "If you have questions about these Terms or wish to report a violation, contact: support@neurotrader-journal.com.",
      },
    ],
  },
  es: {
    title: "Términos de Servicio",
    updated: "Fecha de vigencia: 17 de enero de 2026",
    intro:
      "Estos Términos de Servicio (los \"Términos\") rigen tu acceso y uso del sitio web, las aplicaciones y los servicios relacionados de Neuro Trader Journal (colectivamente, el \"Servicio\") provistos por SG PAX CORP. (\"Neuro Trader Journal\", \"NTJ\", \"nosotros\", \"nos\" o \"nuestro\").",
    important:
      "IMPORTANTE: NTJ es una plataforma de journaling, analítica y educación/coaching. NTJ no es broker-dealer, asesor de inversiones, asesor de trading de commodities ni planificador financiero. Nada en el Servicio pretende ser (ni debe interpretarse como) asesoría de inversión, trading, legal, fiscal o contable.",
    sections: [
      {
        title: "1. Aceptación de los Términos",
        body:
          "AL ACCEDER O UTILIZAR EL SERVICIO, ACEPTAS QUEDAR VINCULADO POR ESTOS TÉRMINOS. SI NO ESTÁS DE ACUERDO, NO ACCEDAS NI UTILICES EL SERVICIO. Podemos actualizar estos Términos periódicamente. Los Términos actualizados serán efectivos cuando se publiquen o se pongan a tu disposición. El uso continuado del Servicio después de una actualización constituye aceptación de los Términos actualizados.",
      },
      {
        title: "2. Descripción del Servicio",
        body:
          "El Servicio puede incluir funciones como journaling de trades, analítica de trading, métricas de rendimiento, etiquetas y notas, screenshots y adjuntos, dashboards, integraciones con plataformas de terceros, funciones comunitarias o de compartición (si están habilitadas), y coaching e insights con IA. Podemos añadir, eliminar o modificar funciones en cualquier momento. Eres responsable de obtener y mantener todos los dispositivos, software y acceso a internet necesarios para usar el Servicio.",
      },
      {
        title: "3. Elegibilidad y registro de cuenta",
        body:
          "Debes tener capacidad legal para celebrar un contrato vinculante en tu jurisdicción para usar el Servicio. Aceptas proporcionar información precisa, actual y completa al crear una cuenta y mantenerla actualizada. Eres responsable de mantener la confidencialidad de tus credenciales y de toda actividad bajo tu cuenta. Notifícanos de inmediato en support@neurotrader-journal.com si sospechas acceso no autorizado.",
      },
      {
        title: "4. Inputs de datos, integraciones y responsabilidad del usuario",
        body:
          "La precisión y utilidad del journaling, analítica, métricas y outputs de AI Coaching dependen de la calidad y completitud de los datos que proporcionas y/o autorizas a NTJ a importar mediante integraciones. Eres exclusivamente responsable de: (1) ingresar, subir o importar tu data de trading de forma correcta y completa; (2) revisar la data importada para asegurar exactitud (fills, comisiones, fees, timestamps, detalles del instrumento); (3) confirmar que la data de tu broker, prop firm o plataforma es precisa y coincide con tus registros oficiales; y (4) entender cómo tu broker/plataforma calcula métricas (por ejemplo, PnL realizado vs. no realizado, PnL neto vs. bruto). Reconoces que las integraciones de terceros pueden estar no disponibles, retrasadas, incompletas o inexactas por causas fuera de nuestro control.",
      },
      {
        title: "5. AI Coaching e insights asistidos por IA",
        body:
          "El Servicio puede proporcionar coaching con IA, detección de patrones, resúmenes, recomendaciones, revisiones de trades, prompts de riesgo/mindset y otros insights automatizados (\"AI Coaching\"). AI Coaching se brinda con fines informativos y educativos.",
      },
      {
        title: "5.1 La IA puede ser inexacta o incompleta",
        body:
          "Los outputs de AI Coaching son generados por sistemas automáticos y pueden contener errores, omisiones, alucinaciones, supuestos incorrectos o información desactualizada. No garantizamos la exactitud, completitud o utilidad de los outputs.",
      },
      {
        title: "5.2 La IA depende de tus datos y contexto",
        body:
          "AI Coaching analiza información basada en los datos que ingresas, subes, importas o proporcionas (incluyendo data de trading, notas, etiquetas y preferencias). Como depende de tus inputs, eres responsable de que sean precisos y completos. Inputs incorrectos pueden generar outputs engañosos.",
      },
      {
        title: "5.3 Sin asesoría financiera; debes evaluar por tu cuenta",
        body:
          "AI Coaching no es asesoría de inversión ni recomendación para comprar o vender ningún instrumento. Cualquier acción basada en AI Coaching es bajo tu propio criterio y riesgo. Debes evaluar de forma independiente cualquier sugerencia, recomendación o análisis antes de actuar.",
      },
      {
        title: "5.4 Asunción de riesgo",
        body:
          "Asumes todos los riesgos asociados a usar o confiar en AI Coaching, incluyendo pérdidas, oportunidades perdidas o resultados adversos. NTJ no asume responsabilidad por decisiones tomadas con base en AI Coaching.",
      },
      {
        title: "6. Divulgación de riesgo de trading",
        body:
          "El trading y la inversión implican riesgo sustancial y no son adecuados para todos. El rendimiento pasado no es indicativo de resultados futuros. Eres responsable de determinar si una estrategia, instrumento o enfoque es apropiado para ti.",
      },
      {
        title: "7. Conducta del usuario",
        body:
          "Aceptas no usar el Servicio para: violar leyes o regulaciones; infringir propiedad intelectual o privacidad; subir malware o intentar acceder de forma no autorizada; acosar o discriminar; suplantar identidad; o usar el Servicio para spam o solicitación comercial no autorizada. Podemos investigar y tomar medidas, incluyendo eliminar contenido, suspender cuentas o terminar acceso para hacer cumplir estos Términos.",
      },
      {
        title: "8. Contenido del usuario y permisos",
        body:
          "Conservas la propiedad del contenido que envías al Servicio (data de trades, notas, imágenes, adjuntos, etc.) (\"Contenido del Usuario\"). Concedes a NTJ una licencia no exclusiva, mundial y libre de regalías para alojar, almacenar, procesar, reproducir y mostrar el Contenido del Usuario según sea necesario para operar y mejorar el Servicio. Si habilitas funciones públicas, otros usuarios pueden ver ese contenido. Eres responsable de no compartir información confidencial que no estés autorizado a divulgar.",
      },
      {
        title: "9. Suscripciones, facturación y cancelaciones",
        body:
          "Ciertas funciones requieren suscripción de pago. Las tarifas se facturan por adelantado de forma recurrente (mensual o anual) salvo indicación contraria en el checkout. Nos autorizas (y a nuestro procesador) a cobrar el método de pago seleccionado. Puedes cancelar en cualquier momento; la cancelación detiene renovaciones futuras y conservas acceso hasta el final del periodo pagado. Reembolsos: salvo que la ley exija lo contrario o NTJ lo indique por escrito, las tarifas no son reembolsables.",
      },
      {
        title: "10. Servicios y enlaces de terceros",
        body:
          "El Servicio puede integrarse o enlazar con servicios de terceros. Estos servicios no están bajo nuestro control. No los respaldamos ni somos responsables de su disponibilidad, exactitud, seguridad, términos o prácticas de privacidad.",
      },
      {
        title: "11. Propiedad intelectual",
        body:
          "El Servicio, incluyendo software, diseño, logos, marcas y contenido provisto por NTJ (excluyendo Contenido del Usuario), pertenece a NTJ y/o licenciantes y está protegido por leyes de propiedad intelectual. Sujeto al cumplimiento de estos Términos, NTJ te concede una licencia limitada, no exclusiva, no transferible y revocable para acceder y usar el Servicio para uso personal o interno.",
      },
      {
        title: "12. Renuncias",
        body:
          "EL SERVICIO (INCLUYENDO AI COACHING) SE OFRECE \"TAL CUAL\" Y \"SEGÚN DISPONIBILIDAD\". EN LA MÁXIMA MEDIDA PERMITIDA POR LA LEY, NTJ RENUNCIA A TODAS LAS GARANTÍAS, EXPRESAS O IMPLÍCITAS, INCLUYENDO GARANTÍAS IMPLÍCITAS DE COMERCIABILIDAD, IDONEIDAD PARA UN PROPÓSITO PARTICULAR, NO INFRACCIÓN Y CUALQUIER GARANTÍA DERIVADA DEL CURSO DE NEGOCIOS O USO COMERCIAL. NO GARANTIZAMOS QUE EL SERVICIO SEA ININTERRUMPIDO, LIBRE DE ERRORES, SEGURO, NI QUE CUALQUIER DATO O RESULTADO (MÉTRICAS, PNL O OUTPUTS DE IA) SEA PRECISO O CONFIABLE.",
      },
      {
        title: "13. Limitación de responsabilidad",
        body:
          "EN LA MÁXIMA MEDIDA PERMITIDA POR LA LEY, NTJ Y SUS AFILIADOS NO SERÁN RESPONSABLES POR DAÑOS INDIRECTOS, INCIDENTALES, ESPECIALES, CONSECUENCIALES, EJEMPLARES O PUNITIVOS, O POR PÉRDIDA DE GANANCIAS, INGRESOS, DATOS O GOODWILL, DERIVADOS DEL USO O INCAPACIDAD DE USO DEL SERVICIO, INCLUYENDO CUALQUIER CONFIANZA EN AI COACHING. EN LA MÁXIMA MEDIDA PERMITIDA POR LA LEY, LA RESPONSABILIDAD TOTAL DE NTJ NO EXCEDERÁ EL MONTO PAGADO A NTJ POR EL SERVICIO EN LOS DOCE (12) MESES ANTERIORES AL EVENTO QUE DIO ORIGEN AL RECLAMO. ALGUNAS JURISDICCIONES NO PERMITEN CIERTAS LIMITACIONES, POR LO QUE ALGUNAS LIMITACIONES PUEDEN NO APLICARTE.",
      },
      {
        title: "14. Indemnización",
        body:
          "Aceptas defender, indemnizar y mantener indemne a NTJ y sus Afiliados frente a cualquier reclamo, daño, responsabilidad, pérdida o gasto (incluyendo honorarios razonables de abogados) derivados de tu uso del Servicio, tu Contenido del Usuario, tu violación de estos Términos o la violación de derechos de terceros.",
      },
      {
        title: "15. Terminación",
        body:
          "Podemos suspender o terminar tu acceso al Servicio en cualquier momento, con o sin aviso, si creemos razonablemente que has violado estos Términos o si debemos hacerlo para cumplir la ley, proteger el Servicio o prevenir daños. Puedes dejar de usar el Servicio en cualquier momento. Al terminar, tu derecho de uso cesa. Ciertas disposiciones sobreviven a la terminación, incluyendo propiedad intelectual, renuncias, limitación de responsabilidad e indemnización.",
      },
      {
        title: "16. Ley aplicable y resolución de disputas",
        body:
          "Estos Términos se rigen por las leyes de la jurisdicción en la que NTJ está establecida, sin aplicar principios de conflicto de leyes. Aceptas que cualquier disputa relacionada con estos Términos o el Servicio será presentada ante tribunales competentes en esa jurisdicción, salvo que la ley aplicable disponga lo contrario.",
      },
      {
        title: "17. Avisos",
        body:
          "Podemos enviarte avisos mediante el Servicio, correo electrónico u otros medios razonables. Los avisos a NTJ deben enviarse a support@neurotrader-journal.com.",
      },
      {
        title: "18. Misceláneos",
        body:
          "Acuerdo completo: estos Términos constituyen el acuerdo completo entre tú y NTJ. Separabilidad: si alguna disposición es inválida, el resto permanece vigente. No renuncia: la falta de aplicación no es renuncia. Cesión: no puedes ceder tus derechos u obligaciones sin consentimiento; nosotros podemos ceder. Fuerza mayor: no somos responsables por demoras o fallas fuera de nuestro control razonable.",
      },
      {
        title: "19. Contacto",
        body:
          "Si tienes preguntas sobre estos Términos o deseas reportar una violación, contáctanos en: support@neurotrader-journal.com.",
      },
    ],
  },
};

export default function TermsPage() {
  const { theme, locale } = useAppSettings();
  const lang = resolveLocale(locale);
  const isLight = theme === "light";
  const isEs = lang === "es";
  const content = isEs ? CONTENT.es : CONTENT.en;

  return (
    <main className={isLight ? "min-h-screen bg-slate-50 text-slate-900" : "min-h-screen bg-slate-950 text-slate-50"}>
      <div className="max-w-5xl mx-auto px-6 md:px-10 py-12 space-y-10">
        <header className="flex flex-col gap-4">
          <div className="flex items-center gap-4">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="/neurotrader-logo.svg" alt="Neuro Trader" className="h-28 md:h-32 w-auto" />
            <div>
              <p className="text-[11px] uppercase tracking-[0.3em] text-emerald-400">
                {isEs ? "Términos" : "Terms"}
              </p>
              <h1 className="text-3xl md:text-4xl font-semibold">{content.title}</h1>
              <p className="text-sm text-slate-400 mt-2">{content.updated}</p>
            </div>
          </div>
          <p className="text-sm text-slate-400 max-w-3xl">{content.intro}</p>
          <p className="text-sm text-amber-200 max-w-3xl">{content.important}</p>
          <div className="flex flex-wrap gap-3 text-[11px]">
            <Link href="/privacy" className="rounded-full border border-slate-700 px-3 py-1 text-slate-300 hover:border-emerald-400 hover:text-emerald-200">
              {isEs ? "Política de Privacidad" : "Privacy Policy"}
            </Link>
            <Link href="/contact" className="rounded-full border border-slate-700 px-3 py-1 text-slate-300 hover:border-emerald-400 hover:text-emerald-200">
              {isEs ? "Contactar soporte" : "Contact support"}
            </Link>
          </div>
        </header>

        <section className="space-y-6">
          {content.sections.map((section) => (
            <div
              key={section.title}
              className={isLight ? "rounded-2xl border border-slate-200 bg-white p-5" : "rounded-2xl border border-slate-800 bg-slate-900/70 p-5"}
            >
              <h2 className="text-lg font-semibold text-slate-100">{section.title}</h2>
              <p className="mt-2 text-sm text-slate-300 leading-relaxed">{section.body}</p>
            </div>
          ))}
        </section>
      </div>
    </main>
  );
}
